# GRIB2 products

Freezing rain precipitation rate [spread]:
    Variable:
        EN: Freezing rain precipitation rate
        FR: Taux de pluie verglaçante
    Abbreviation: FPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Heat index [spread]:
    Variable:
        EN: Heat index
        FR: Humidex
    Abbreviation: HEATX
    Unit:
        EN: K
        FR: K

Geopotential height [spread]:
    Variable:
        EN: Geopotential height
        FR: Hauteur géopotentielle
    Abbreviation: HGT
    Unit:
        EN: gpm
        FR: gpm

Ice pellets precipitation rate [spread]:
    Variable:
        EN: Ice pellets precipitation rate
        FR: Taux de précipitation du grésil
    Abbreviation: IPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Pressure reduced to MSL [spread]:
    Variable:
        EN: Pressure reduced to Mean Sea Level
        FR: Pression réduite au niveau moyen de la mer
    Abbreviation: PRMSL
    Unit:
        EN: Pa
        FR: Pa

Rain precipitation rate [spread]:
    Variable:
        EN: Rain precipitation rate
        FR: Taux de précipitation de pluie
    Abbreviation: RPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Snow precipitation rate [spread]:
    Variable:
        EN: Snow precipitation rate
        FR: Taux de précipitation de neige
    Abbreviation: SPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Temperature [spread]:
    Variable:
        EN: Temperature
        FR: Température
    Abbreviation: TMP
    Unit:
        EN: K
        FR: K

Total precipitation rate [spread]:
    Variable:
        EN: Total precipitation rate
        FR: Taux de précipitation totale
    Abbreviation: TPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Wind chill factor [spread]:
    Variable:
        EN: Wind chill factor
        FR: Facteur de refroidissement éolien
    Abbreviation: WCF
    Unit:
        EN: K
        FR: K

Wind speed [spread]:
    Variable:
        EN: Wind speed
        FR: Vitesse du vent
    Abbreviation: WIND
    Unit:
        EN: m/s
        FR: m/s

Freezing rain precipitation rate Percentile:
    Variable:
        EN: Freezing rain precipitation rate
        FR: Taux de pluie verglaçante
    Abbreviation: FPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Heat index Percentile:
    Variable:
        EN: Heat index
        FR: Humidex
    Abbreviation: HEATX
    Unit:
        EN: K
        FR: K

Ice pellets precipitation rate Percentile:
    Variable:
        EN: Ice pellets precipitation rate
        FR: Taux de précipitation du grésil
    Abbreviation: IPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Rain precipitation rate Percentile:
    Variable:
        EN: Rain precipitation rate
        FR: Taux de précipitation de pluie
    Abbreviation: RPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Snow precipitation rate Percentile:
    Variable:
        EN: Snow precipitation rate
        FR: Taux de précipitation de neige
    Abbreviation: SPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Temperature Percentile:
    Variable:
        EN: Temperature
        FR: Température
    Abbreviation: TMP
    Unit:
        EN: K
        FR: K

Total cloud cover Percentile:
    Variable:
        EN: Total cloud cover
        FR: Couverture nuageuse totale
    Abbreviation: TCDC
    Unit:
        EN: '%'
        FR: '%'

Total precipitation rate Percentile:
    Variable:
        EN: Total precipitation rate
        FR: Taux de précipitation totale
    Abbreviation: TPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Wind chill factor Percentile:
    Variable:
        EN: Wind chill factor
        FR: Facteur de refroidissement éolien
    Abbreviation: WCF
    Unit:
        EN: K
        FR: K

Wind speed Percentile:
    Variable:
        EN: Wind speed
        FR: Vitesse du vent
    Abbreviation: WIND
    Unit:
        EN: m/s
        FR: m/s

Prob of Total precipitation rate:
    Variable:
        EN: Total precipitation rate
        FR: Taux de précipitation totale
    Abbreviation: TPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Prob of Total precipitation:
    Variable:
        EN: Total precipitation
        FR: Précipitation totale
    Abbreviation: APCP
    Unit:
        EN: kg/(m<sup>2</sup>)
        FR: kg/(m<sup>2</sup>)

Prob of Freezing rain precipitation rate:
    Variable:
        EN: Freezing rain precipitation rate
        FR: Taux de pluie verglaçante
    Abbreviation: FPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Prob of Ice pellets precipitation rate:
    Variable:
        EN: Ice pellets precipitation rate
        FR: Taux de précipitation du grésil
    Abbreviation: IPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Prob of Rain precipitation rate:
    Variable:
        EN: Rain precipitation rate
        FR: Taux de précipitation de pluie
    Abbreviation: RPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Prob of Snow precipitation rate:
    Variable:
        EN: Snow precipitation rate
        FR: Taux de précipitation de neige
    Abbreviation: SPRATE
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

Prob of Temperature:
    Variable:
        EN: Temperature
        FR: Température
    Abbreviation: TMP
    Unit:
        EN: K
        FR: K

Prob of Wind speed (gust):
    Variable:
        EN: Wind speed (gust)
        FR: Vitesse du vent (rafale)
    Abbreviation: GUST
    Unit:
        EN: m/s 
        FR: m/s

Prob of Wind speed:
    Variable:
        EN: Wind speed
        FR: Vitesse du vent
    Abbreviation: WIND
    Unit:
        EN: m/s
        FR: m/s

Prob of Heat index:
    Variable:
        EN: Heat index
        FR: Humidex
    Abbreviation: HEATX
    Unit:
        EN: K
        FR: K

Prob of Wind chill factor:
    Variable:
        EN: Wind chill factor
        FR: Facteur de refroidissement éolien
    Abbreviation: WCF
    Unit:
        EN: K
        FR: K
