APCP:
    Variable:
        EN: Total precipitation
        FR: Précipitation totale
    Unit:
        EN: kg/(m<sup>2</sup>)
        FR: kg/(m<sup>2</sup>)

FPRATE:
    Variable:
        EN: Freezing rain precipitation rate
        FR: Taux de pluie verglaçante
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

GUST:
    Variable:
        EN: Wind speed (gust)
        FR: Vitesse du vent (rafale)
    Unit:
        EN: m/s
        FR: m/s

HEATX:
    Variable:
        EN: Heat index
        FR: Humidex
    Unit:
        EN: K
        FR: K

HGT:
    Variable:
        EN: Geopotential height
        FR: Hauteur géopotentielle
    Unit:
        EN: gpm
        FR: gpm

IPRATE:
    Variable:
        EN: Ice pellets precipitation rate
        FR: Taux de précipitation du grésil
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

PRMSL:
    Variable:
        EN: Pressure reduced to Mean Sea Level
        FR: Pression réduite au niveau moyen de la mer
    Unit:
        EN: Pa
        FR: Pa

RPRATE:
    Variable:
        EN: Rain precipitation rate
        FR: Taux de précipitation de pluie
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

SPRATE:
    Variable:
        EN: Snow precipitation rate
        FR: Taux de précipitation de neige
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

TCDC:
    Variable:
        EN: Total cloud cover
        FR: Couverture nuageuse totale
    Unit:
        EN: '%'
        FR: '%'

TMP:
    Variable:
        EN: Temperature
        FR: Température
    Unit:
        EN: K
        FR: K

TPRATE:
    Variable:
        EN: Total precipitation rate
        FR: Taux de précipitation totale
    Unit:
        EN: kg/(m<sup>2</sup>*s)
        FR: kg/(m<sup>2</sup>*s)

WCF:
    Variable:
        EN: Wind chill factor
        FR: Facteur de refroidissement éolien
    Unit:
        EN: K
        FR: K

WIND:
    Variable:
        EN: Wind speed
        FR: Vitesse du vent
    Unit:
        EN: m/s
        FR: m/s

