name: mkdocs deploy
on:
  release:
    types: [published]
jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out release commit
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs==1.3.0 mkdocs-jupyter==0.20.1 lxml_html_clean
    - name: Build documentation
      run: mkdocs build
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        user_name: DPS Client
        user_email: DPS-Client@ec.gc.ca
        commit_message: updated via release ${{ github.event.release.tag_name }}
